# create post
post http://localhost:7777/api/customTopicSearch/createcustomtopic
Content-Type: application/json

{
    "name": "cognilium380",
    "match_type": "qwe",
    "any_keywords": ["onww" ,"two", "etc"],
    "must_also_keywords": ["12", "abx", "bax", "xab"],
    "must_not_contains_keywords": ["000", "aaa",  "1p1"],
    "exclude_domains": ["twitter.com", "facebook.com"],
    "limit_domains_results": ["www.ncmaz", "www.cognilium", "www.insta"],
    "enddate": "2021-11-03",
    "startdate": "2021-11-02",
    "language": "urdu"

}

###

# get all custom topics
get http://localhost:7777/api/customTopicSearch/getcustomtopics


###

# update a single custom topic by customTopic ID
PATCH http://localhost:7777/api/customTopicSearch/updatecustomtopic/6239a1f76184bf0beb9e37ef
Content-Type: application/json

{
    "name": "covid-2",
    "match_type": "abc",
    "any_keywords": ["saad" ,"asda", "asdasbd"],
    "must_also_keywords": ["123", "abc", "xyz", "pqr"],
    "must_not_contains_keywords": ["123", "abc", "xyz", "pqr"],
    "exclude_domains": ["amazon.com", "google.com"],
    "limit_domains_results": ["ww.amazon", "www.saad.com", "google.com"],
    "enddate": "2021-11-03",
    "startdate": "2021-11-02",
    "language": "urdu"

}


###
# delete a custom topic by topic-id
DELETE http://localhost:7777/api/customTopicSearch/deletecustomtopic/

