# create a poster
post http://localhost:7777/api/favouritesFolder/
Content-Type: application/json

{
    "folderName": "Crypto currency"
}

###

# get a single folder by folder id
GET http://localhost:7777/api/favouritesFolder/6213c26202d9fe10c46dc498


###

# get a all favourites folder by user id
GET http://localhost:7777/api/favouritesFolder/

###


# delete folder by folder id 
DELETE http://localhost:7777/api/favouritesFolder/6218b373aad0e01feeae4682


###
# updating folder by folder id
PATCH http://localhost:7777/api/favouritesFolder/6213c28f02d9fe10c46dc49a
Content-Type: application/json

{
  "folderName": "Crypto currency"
}



 
