# registering a user
post http://localhost:7777/api/user/register
Content-Type: application/json

{
    "email":"saad@gmail22.com",
    "password":"saad",
    "firstName": "Shaikh Muhammad ",
    "lastName": "Saad",
    "title": " hello im Saad"
}

###

# Verifying a user by email
POST http://localhost:7777/api/user/verify-email
Content-Type:  application/json

{
    "token": "cde2ae7780902e527580af13121c2b1596b9b97b2d36062ae9b80914e8be18a8950a8d14a55ef105"
}

###

# user sign in / authenticate
post http://localhost:7777/api/user/authenticate
Content-Type:  application/json

{
    "email":"saad@gmail22.com",
    "password":"saad"
}

###
# revoking token
post http://localhost:7777/api/user/verify-email
Content-Type:  application/json

{

}


###
#forget password route
post http://localhost:7777/api/user/forgot-password
Content-Type:  application/json

{
    "email":"saad@gmail22.com"
}


###
#Reset password route
post http://localhost:7777/api/user/reset-password
Content-Type:  application/json

{

"token" : "70814680b9443e6a462c5fd73dad2079774302d119b525bb378a208502f74de242edb673832d1d6b", 
"password": "saad01"

}

