# registering a user
post http://localhost:7777/api/user/register
Content-Type: application/json

{
    "email" : "saad@gmail24.com",
    "password" : "saad01",
    "firstName" : "saadR Idrees",
    "lastName" : "saad i drees",
    "title" : "hello im Saad"
}

###

# Verifying a user by email
POST http://localhost:7777/api/user/verify-email
Content-Type:  application/json

{
    "token": "6f82d215a5a14bdd0a24c23b11f74bce75a86a269516cf23e4fe18ed77d358174d6580d5c808807f"
}

###

# user sign in / authenticate
post http://localhost:7777/api/user/authenticate
Content-Type:  application/json

{
    "email":"saad@gmail25.com",
    "password":"saad03333829172"
}

###
# revoking token
post http://localhost:7777/api/user/revoke-token
Content-Type:  application/json

{

}


###
#forget password route
post http://localhost:7777/api/user/forgot-password
Content-Type:  application/json

{
    "email":"saad@gmail25.com"
}


###
#Reset password route
post http://localhost:7777/api/user/reset-password
Content-Type:  application/json

{

"token" : "802387052954d6a3a6f888f531149867a1bbf842f20498c5d9b1db76e46c130fbe0d5146b42d3abf", 
"password": "saad01"

}

###
# refresh token first need to be authenticated
post http://localhost:7777/api/user/refresh-token
Content-Type: application/json

{
    
}

###

# Update user data first need to be authenticated
put http://localhost:7777/api/user/619df47da46e8177b22e17ad
Content-Type:  application/json

{
    "email":"saad@gmail22.com",
    "password":"saad01",
    "firstName": "Shaikh Muhammad",
    "lastName": "Sad",
    "title": " hello im Saad"
}


###

# delete user first need to be authenticated
delete http://localhost:7777/api/user/619df47da46e8177b22e17ad
Content-Type:  application/json

{
    
}



###
# get Favourites Folder
get http://localhost:7777/api/favouritesFolder/
Content-Type: application/json

{
    
}




