# registering a user
post http://localhost:7777/api/user/register
Content-Type: application/json

{
    "email":"saad1@gmail.com",
    "password":"saad01",
    "firstName":"Saad", 
    "lastName":"Idrees",
    "title":"Mr"

}

###

# Verifying a user by email
POST http://localhost:7777/api/user/verify-email
Content-Type:  application/json

{
    "token": "52b22005cf615a6706f7551781fd45d2b998002c17968799fe62fb647b0d2a4649c752edc6eb3e44"
}

###

# user sign in / authenticate
post http://localhost:7777/api/user/authenticate
Content-Type:  application/json

{
    "email":"saad_idrees@gmail.com",
    "password":"saad_idrees"

}

###
# revoking token/ log-out
post http://localhost:7777/api/user/revoke-token
Content-Type:  application/json

{

}


###
#forget password route
post http://localhost:7777/api/user/forgot-password
Content-Type:  application/json

{
    "email":"saad@gmail25.com"
}


###
#Reset password route
post http://localhost:7777/api/user/reset-password
Content-Type:  application/json

{

"token" : "802387052954d6a3a6f888f531149867a1bbf842f20498c5d9b1db76e46c130fbe0d5146b42d3abf", 
"password": "saad01"

}

###
# refresh token first need to be authenticated
post http://localhost:7777/api/user/refresh-token
Content-Type: application/json

{
    
}

###

# Update user data first need to be authenticated
put http://localhost:7777/api/user/621c99bc0beb76ccd0966e6f
Content-Type:  application/json

{
    "email":"saad@gmail22.com",
    "password":"saad01",
    "firstName": "Shaikh Muhammad",
    "lastName": "Saad",
    "title": " hello im Saad"
}


###

# delete user first need to be authenticated
delete http://localhost:7777/api/user/619df47da46e8177b22e17ad
Content-Type:  application/json

{
    
}




